export enum ValidateAuthFormError {
    NO_DATA = 'NO_DATA',
    SERVER_ERROR = 'SERVER_ERROR',
    INCORRECT_AUTH_FORM_DATA = 'INCORRECT_AUTH_FORM_DATA',
    INCORRECT_AUTH_FORM_USERNAME = 'INCORRECT_AUTH_FORM_USERNAME',
    INCORRECT_AUTH_FORM_PASSWORD = 'INCORRECT_AUTH_FORM_PASSWORD',
}
