export { getDeletePortfolioError } from './model/selectors/getDeletePortfolioError/getDeletePortfolioError'
export { getDeletePortfolioLoading } from './model/selectors/getDeletePortfolioLoading/getDeletePortfolioLoading'
export { deletePortfolio } from './model/services/deletePortfolio/deletePortfolio'
export { deletePortfolioActions,deletePortfolioReducer } from './model/slice/deletePortfolioSlice'
export type { DeletePortfolioSchema } from './model/types/deletePortfolio'
export { DeletePortfolioModal } from './ui/DeletePortfolioModal/DeletePortfolioModal'
