export { getUploadAvatarError } from './model/selectors/getUploadAvatarError/getUploadAvatarError'
export { getUploadAvatarLoading } from './model/selectors/getUploadAvatarLoading/getUploadAvatarLoading'
export { uploadAvatar } from './model/services/uploadAvatar/uploadAvatar'
export { uploadAvatarActions,uploadAvatarReducer } from './model/slice/uploadAvatarSlice'
export type { UploadAvatar, UploadAvatarSchema } from './model/types/uploadPortfolio'
export { UploadAvatarModal } from './ui/UploadAvatarModal/UploadAvatarModal'
